package com.example.demo.entity;

import java.math.BigDecimal;

public class Work {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.id
     *
     * @mbggenerated Wed Jan 02 09:33:17 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.salary
     *
     * @mbggenerated Wed Jan 02 09:33:17 CST 2019
     */
    private BigDecimal salary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.dept_id
     *
     * @mbggenerated Wed Jan 02 09:33:17 CST 2019
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.name
     *
     * @mbggenerated Wed Jan 02 09:33:17 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.id
     *
     * @return the value of work.id
     *
     * @mbggenerated Wed Jan 02 09:33:17 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.id
     *
     * @param id the value for work.id
     *
     * @mbggenerated Wed Jan 02 09:33:17 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.salary
     *
     * @return the value of work.salary
     *
     * @mbggenerated Wed Jan 02 09:33:17 CST 2019
     */
    public BigDecimal getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.salary
     *
     * @param salary the value for work.salary
     *
     * @mbggenerated Wed Jan 02 09:33:17 CST 2019
     */
    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.dept_id
     *
     * @return the value of work.dept_id
     *
     * @mbggenerated Wed Jan 02 09:33:17 CST 2019
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.dept_id
     *
     * @param deptId the value for work.dept_id
     *
     * @mbggenerated Wed Jan 02 09:33:17 CST 2019
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.name
     *
     * @return the value of work.name
     *
     * @mbggenerated Wed Jan 02 09:33:17 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.name
     *
     * @param name the value for work.name
     *
     * @mbggenerated Wed Jan 02 09:33:17 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}