package com.example.demo.dao;

import com.example.demo.entity.Work;

import java.util.List;

public interface WorkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbggenerated Wed Jan 02 09:33:17 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbggenerated Wed Jan 02 09:33:17 CST 2019
     */
    int insert(Work record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbggenerated Wed Jan 02 09:33:17 CST 2019
     */
    int insertSelective(Work record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbggenerated Wed Jan 02 09:33:17 CST 2019
     */
    Work selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbggenerated Wed Jan 02 09:33:17 CST 2019
     */
    int updateByPrimaryKeySelective(Work record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbggenerated Wed Jan 02 09:33:17 CST 2019
     */
    int updateByPrimaryKey(Work record);
    List<Work> findAll();
}